* <2024-08-26 h>

** Paár Dávid
Némi értetlenkedés után köszöntött. RRF keretében zajlik az oktatás.

** Pásztor Enikő
Digitális transzformáció mérföldkő. Nem véletlen, hogy kötelező.
Nagyon fontos oktatás, ami kötelző. Ébredjünk fel. Fontos mérföldkő.
Mindenkinek meg kell megugrani. Ne csak végigülni. Értően figyelni.

** Paár Dávid
DTO (Digigális Transzformáció az Oktatásban) fő láb a moodle felület megújítása.
Régi felület ráncfelvarrás. Vadonat új moodle a tanév elejétő kezdve. Ismerkedni.

Három alkalommal kötelező oktatás. Fakultatív szeptemberi alkalmak. Minden alkalom
tematikája. Mindenkinek fiók létrehozva. Néhány gyakorló feladat csatlakozik.
A frissített felület mellett nem áll meg a fejlesztés. Aki fejlesztett, annak anyagai
megvannak. Támogatás, segytés.

Ma Vágvölgyi Csaba moodle rendszer frissítése. Papp Gyula kollégával együtt. Róluk
tudni, hogy számos moodle bevezetése Debreceni Egyetem. Hazai moodle közösség motorjai.
Gazdag tapasztalatok. Kérdés feltevés, probléma esetén is segítenek.

** Vágvölgyi Csaba
Szép számmal vagyunk. Megújult elarning (moodle) rendszer. Megkerülhetetlen, ma már
a COVID kényszer helyzet után szinte kötelező. Blended learning megkerülhetetlen. Minden
egyetemen jelen van.

https://moodle.uni-sopron.hu

Most már az új érhető el. Korábbiak is elérhetők. Régi:
https://moodle-old.uni-sopron.hu még él, de az induló félévben csak az új rendszerben
dolgozzunk. Szerkesztési jogosultságok elvéve. Archív renszerként ott marad. Ambrus
Attila költöztetne. Átemelhető kurzusok. Új renszer, újabb verzió.

Költöztetéssel kapcsolatban lesz kommunikáció. Új renszert gondozni. Néhány héten
belül lekapcsolt szerkesztési jog.

*** Új renszer
Még változik változhat. Egyedi igények. 90% már vizuális megjelneés.

**** Felépítés
Slider aktuális ügyek.

Elérhetők lesznek kézikönyvek az új rendszerhez. A végleges vizualitással készülnek.

Kurzus kategóriák az Egyetem felépítéséhez. Gyakorló kurzus moodle képzésben 439 kurzus
létrehozva. Részben új, részben régi kurzus.

*** Bejelentkezés
kipróbálni. Nyitó ablakon nem. Jobb felső belépés gomb.  Két mdon
belépés. Adminisztrátori belépés még van, de eltűnik. O365 fiókkal
megy. Egy gombnyomással bejelentekzni, ha böngészőben bejelentkeztél, ha nem feldobja.

Bejelentkezés mőködik.

*** Irányítópult
Mindenkori kurzus. Utalások, naptár, időzített feladat. Timeline.

Átirányít bennónket valahonnan ide.

Balfelső soproni egyetem logó ide dob minket. Portál kezdőoldalak  Kezdőoldal gommbbal.

Navigáció saját gyakorló kurzusban. 4-es benyúlt kurzus navigációba.

Tallálunk menüpontokat a fejlécben. Mindig ott vannak.

DNS átállási hiba. Régi oldalnak kellene betöltődni.

- Kurzus kezdő pont
-

**** Bejelentkezési gond
Több tipp. Más böngészőből. Kis türelmet krértek.

DNS cache. Start cmd futtatás rendszergazdaként jobb gomb.
ipconfig parancs kiírja az

ipconfig /flushdns

IP cím: 193.225.93.45-nek kell lennie

***** Feladat lista
Utólag kapunk. Nem gond, ha nem veszünk részt interaktívan.

hosts fájl is működik.
c:\Windows\System32\drivers\etc\hosts

Ide be lehet írni.

193.225.93.45 moodle.uni-sopron.hu

**** Folyt
Radikálisan átalakítva

Moodle közösségen belül tagsági díjas rész van. Ha befizettem, akkor jogosultságom
van, hogy merre menjen a moodle fejlesztés. Egybehangzó kérés volt, hogy egységesíteni
kellene és átgondolni a felhasználói felületet.

Korábban bal oldalon sok menü. Bal, jobb. Ez most középen, ami korábban ki volt pakolva.
Gombnyomással elérni menüt vagy menücsoportot. Eltüntethető.

Tananyag és tevékenység  bal oldalon. Tartalomjegyzékként működik.

Jobb oldali  lokk, csak a billenő szerkesztési bekapcolás.

Jobb oldalt én döntöm el, hogy mi jelenjen meg.

Moodle Moduláris OO dinamikus Learning Envrironment. Rengeteg blokk van.

Kurzus a fő, itt tudunk visszatérni. Visszajutok a kurzus felületére.

**** Beállítások
Menü. Beállítások. 30 embernél kérdéses, hogy mi a valódi felhasználó neve.

**** Résztvevők
Belépve bal felső sarok. Tanulóink beíratva. Kézi beíratás.
Pénteken. Csoportok létrehozás.

Engedélyek, csoportos kiíratás. Neptunnal szinkronizált.

**** Osztályzatok
Pénteken kivesézve. Gyakorlatilag ez az osztálynapló. Értékelő felület.

Ugyan annyit teljesít, moodle kiszámítja a jegyet. Nem kerül át a neptunban.
SDA ellenállt.

**** Jelentések
Pénteken kivesézzük.

**** További
Kérdés bank, tartalom bank. Tartalom bank H5P modulokra. Adminisztráció
kurzus teljesítés beállítása.

Teljesítés. Kitűzők az hab a tortán. Intézményi vagy oktatói
akarat. Nemzetközi szabvány. Minősítési, értékelési rendszer.
Diplomával egyenértékű digitális kitűző.

*** Jobb oldal
Testre szabható. tananyagok, határidők. Jól követhető, egy blokkban
rakjuk ki a naptárt a tanulók számára. Amint határidős dolgokat rakunk ki,
már látni fogjuk, hogy a különböző dátumok fölött pöttyöcskék.

**** Elkövetkező események
Naptár mellett elkövetkező eseményeket is kirakhatjuk. Adott felhasználó
szabályozhatja. Teljesítendők, hallgatók profiljukban átállíthatják.

Alaphelyzet 10 eseményt tud. Néhány hétre. Hónapokra átállítani!

**** Online felhasználók
Ez a blokk minket szolgál. Célszerű látni, hogy hányan vannak. Online
felhasználók.  Aki az utolsó 5 percben aktív. Csak azon nevek, akik a
kurzusban benne vannak.

**** Teljesítési szint
Hallgatóknak nagyon fontos. Nincs a kurzusban teljesíthez kötött.

Fórumok (több is) lehet. Hírek és információk csak az oktató ír,
fél óra múlva megkapják. Utoléri a hallgató. Se saját kérdés, se.

Teljesítési szint a naptár fölé húzva. Csík látszik. Mi oktatóként
tudjuk, hogy az összes diák hogyan teljesít. Piszkáljuk a lemaradókat.

*** Személyes profil
Beépített szerkesztők használata.

Nem a cimkét követte. Mindenkinek joga van beíépíteni.

*** Értesítések jobb fent
Szóbuborékos ember, csengettyű renszer küldi. Saját avatar. Nem tudjuk
módosítani. Moodle nem módosít. M365 integráció keretében amit oda beállítunk
áthozza. Saját fiókot nem tudjuk módosítani.

*** Profil
Itt:
- Profil
- Pontok mint hallgató. Saját gyakorló kurzusban oktató, közösben
  hallgató vagyok.
- Naptár
- Saját állomány (le lesz nullázva). Oda nem tudunk elhelyezni semmit.
- Jelentések
- Beállítások Sok blokkocska, szerepcsere, blog, mire használható?
  Angolszász világban tanulói napló nagyon fontos. Tanulási napló, itt
  vezethető, behúzható a kurzusba.
- Itt tudok még nyelvet is váltani. Angol-magyar!
- Fórum beállítások nem csevegő felület, fontos beállítási lehetőség.
  Összesített email (nem javasolt). Ha írsz a fórumra, akkor beírat. Fórum
  nyomon követése, hány olvasatlan üzenet.
- Szerkesztő beállítása Tiny MCE az alap
- Üzenetek. Asszinkron forma alapvető. Az intézmények itt cseszték el. Nagy renszer
  igény. Megadni.

*** Címke hozzáadása
Itt szövegszerkesztő.
- Kép beszúrása
- URI beszúrása: Rendszeren kívüli oldlalra hivatkozunk. Új ablakban megnyittatni!
- Multimédia.
- Szövegbe narráció
- H5P tartalom. Mozgalmas kurzus. Önellenőrző kérdések.

Formázás
Billentyű parancsok. Mindkét szövegszerkesztőben men, mint Word vagy Excel.
Minden szövegszerkesztő reszponzív kép. 2.7-ben fix kép, de itt megjelenítéstől
függően változik. Szűkebb hely, akkor aláskáláz!

Táblázat beszúrása.

Office dokumentumból jövő táblázat.

Két féle. Elarning renszer. Nem hagyhatjuk mentetlenül.
Session time: 1 óra. 1 óra 1 perckor a beírtak kuka.
Izgalmas, meddig tekint minket kattintástól-kattintásig bejelentkezettnek.

Wordben van automatikus mentés. Itt nincs. Ide visszatérünk, a
különböző szövegszerkesztők nem egyformák. Csinosítás, látványosítás.
Bizonyos műveletek csak az attóban elérhető. HTML boost editor csak a
másiknál elérhető.

** Itt megint volt technikai szünet Papp Gyula újra
Induljon a banzáj.

Kipróbáljuk a tananyagokat. Statikus tananyagok.
Létező blokkot át tudom húzni. Rossz helyen van, át kell húzni. Bal oldali panaelen is
át tudom helyezni!

Tartalom gyártás előtt:

*** Kurzus képességei
Beállítások menüben.

Kurzus teljes címe. Legyen automatikus! Oktatóként nem tudok kurzust készíteni,
de ha megkaptam, teljes körűen szerkeszthetem. Kurzus teljes neve, a neptunos
hivatalos neve. Ha egy oktató tartja nem probléma, mert a tárgy összes kurzusával
ide rendelhető egy kurzusba. Több csoport jelenik meg! El tudom csoprot szinten
különíteni a hallgatókat. Legyen bent egy neptun kód zárójelben! Akik adminisztrálják
és oktatók segítők így meg tudják találni. Ugyan az a nevű tárgy így azonosítható.

Kurzus rövid nevénél a neptun ismétlődik és félév jelzése.

Kurzus kategória. Rejtett státuszba tesszük. Át akarom alakítani, nem engedem
be a hallgatókat. Ha rejtett, nem tud belépni senki.

Kezdő dátum! Fontos! Sok modul használja. Befejezési időpont. 1 évig enged
kifutni. Ez nem zárja ki a hallgatót, de naptárra hatása van!

Csábító leírás mehet ide. KV vagy V kurzusnál.

Kurzusleíró kép. Beállítható. Webről is lehívható. Képzésre
professzionális képe, amik egyszerűsítik a tartalmat.

**** Kurzusforma
Speciális kurzuselrendezésre lehet  bővíteni.

- Egytevékenységes :: Rögtön abban talája magát. Wiki, stb.
- Fórumforma :: kommunikációs. Lényeg, hogy kommunikálunk nem használjuk.
  Nem oktatási kurzus.
- Tematikus :: alapértelmezett
- Heti :: majd menézük

**** Rejtett részek
Teljesen láthatatlanok. Csak én látom.
Elérketetlen. Diák látja a téma blokk nevét. Most nem elérhető.

**** Kurzus elrendezése
Összes egy oldalon, minden látszik. Oldalanként egy szekció.
Minden blokk látszik összecsukva. Tanulandó blokk látszik. jobb és
bal sarokban témablokkok címként megjelennek. Vízszintesen laposzható.

**** Megjelenés
Nyelv előírása angol vagy magyar. Milyen szinten szabályozza.
Böngésző nyelvi beállítása. Böngésző nyelvét veszi figyelembe.
Ne írja elő. Belépek, akkor a profilban átállított nyelv.
Direkt külföldieknek szóló. Angol nyelv kötelező.

***** Hírek száma
irreleváns
Ha a fórumot használjuk. Elmarad az óra ide kerül.
Egy irányú kommunikáció. Fél óra után levélbe megy.
Hivatalos Debrecenben. Az oktatók egy része itt kommunikál.
Volt ott hivatalos. Milyen email rögzítve. Fontos, hogy ugyan
arra a címre menjen neptunba és elearningbe.

***** Pontok
Hallgató hány pontot kapott

***** Tevékenység megjelnítés
hallgatónak

***** időpont
időpontok

**** Állományok és feltöltések
max 100 MB. Azért nagy fájlokat ne töltsünk fel.
Nagy fájlt hová: Integrálva M365-re! Megosztjuk az oda feltöltötteket.
Saját állományok, Share point tartalmakat ide! Kurzusba ne toljunk filmet.

**** Teljesítmény nyomon követése
Korábban valami négyszöggel. Oda tanulónak kellett kattintani.

Itt nem négyszögünk, szöveges gombunk van. Tesztet nézze meg, legalább
egy próbálkozás.  Egymás alatt egy-egy gombocska. Nem lesz mindig így.

Egy év múlva új moodle renszer. Tovább optimalizálás. Sok soros gombok
egy menübe kerülnek.

**** Csoportok
Alapvetően nincs. Párhuzamos kurzusnál van értelme. Csoportmódot be kell
állítani. El tudom különíteni a hallgatókat. Automatizálható.

Páros munkára csoportok. Alapértelmezett csoportosítás. Adminisztratív
felületen lehet felkeresni, használni. Ha külön álló, akkor nem látják
egymás üzeneteit. Ha látható, akkor a diákok tudják a
csoportváltást. Megnézhetik a másik csoportnak az üzeneteit is. Wiki
már régóta diákmunka. Adott esetben itt projekteltetem a hallgatókat
akkor külön állónál nem látják egymás, ha beállítva, akkor látják.

Csoportos részvétel előírása maradjon nem! Moodleban tudom kezelni.

**** Szerep átnevezése
Nem csak tanítási céllal. Szenátusi kurzus, tanszéki anyagok.

**** Címkék
A moodleban mindenütt ott van. Mindent el tudok látni, címkézni.
Magunkat is tudnánk cimkézni. Tartalmakat címkézni. OSZK hivatalos
tezauroszt csinál az oktatásnak. Tartalmak besorolása.

100ETO klasszikus könyvtári.

Másik cimkékkel kötött szótárból. Intézmény is meghatározható. Teszteknél
lesz jelentősége. Technikai védelmi biztonsági szempontból nem lesz kereshető.

** Szünet
20 perc 10:55-kor.

** Papp folytat
*** Heti-tematikus
A téma 1-X helyett dátum jelenik meg. A hét jelölése automatikus.
Dátumot is felül lehet írni. Kevesen használják a heti bontást.
14 heti blokkot be lehet írni. Attól hogy elarning, nem lesz elarining.
Itt nem igazi. Normál órai doglok kiváltása! Módszertan vagy megközelítés.

Gyakorlati tárgyaknál az elméleti anyagot kiadom előzetes tanulásra.
Önellenőrző tesztet ráépítek. Látni kell. Késlekedő hallgatókat piszkálom.
Milyen tipikus hibákat vétenek. Az órát nem a tananyag elmondásra szentelem,
hanem tudunk az ismeret hasznosítását erősíteni.

Az általános blokk nem tüntethető el. Ide minden hivatalos információ kerül.
Kapnak egy dekoratív cuccot, hírek megmarad és kapnak debrecenben egy kérdező
fórumot. Hivatalos információk könyv. Tematika követelmények, ajánlott és kötelező,
fogadó óra.

*** Rejtés
Nem látják. Volt korában szó.

*** Tanulási információk
A közös kurzusban az oktatási egységekben lesz tartalom. Közös
kurzusból mazsolázhatunk.

Jobb felső sarok mappa letöltés, zippelve. Különböző állományok
másként viselkednek. Döntést kívánnak. pdf bevontatható, ha
szerkesztem a fájlt. Ott az állomány!

Saját fájlal vagy minta állománnyal. Gyula soha sem teszi így be az állományt.
Nem behúz, hanem tevékenység és tananyag.

A nagy táblában fülek. Tevékenységek, tananyagok, ez a statikus.

Csillagozva ki lehet jelölni a megfelelőket. Ez lesz az első.

*** Állomány hozzádása
Multimédiás tanyanyag. Mindig csak egyet tudok megjelölni.

Megjelenítés ne legyen automatikus. Lecseréli. a moodle oldalt. Itt vagy beágyazás és
új oldalra megnyitom.

Tematizálás. Szekció hivatalosan, de tartalmi blokknak hívják ők.
Mi döntjük el, hogy hogyan legyen?

Jobb felső sarok a szerkesztő gomb.

Két fő típus. Gyors, és behúzom. Megjelenő állomány word ikon.

A tananyag beszúrása állomány. Részletes beállítások. Behúzom vagy tallózás.

*** Szokásos modulbeállítások
El is lehet rejteni. Folyamatosan felbukkantatom. Hogyan lehet
függővé tenni a modulokat, azzal szabályozhatom.

Csak olyan tevékenységek, amivel tudok számolni. Teszt, bármi, amiből pontot
lehet szerezni! Mindenki ugyan annyi feladatot kell csináljon. ott kell a szám.

*** Tevékenység teljesítése
Kézzel megjelölés gondot jelent, Lehetőleg automatikus legyen Ha a feltételek teljesülnek
az az automatuks.

Meg kell tekinteni a teljestéshez. Bekapcsolták az új ablakban a doltot.

Új állományok képek videók hang állomány.

*** Kép behúzása
Felajánlja médi a behúzása, feltöltés. Csak a cím jelenik
meg. Rákattint a kép új ablakban megjelnik.

*** Hang videó
mp3 hang
mp4 videó

Ebben az esetben lejátszó rendelődik hozzá.

Első felület, második feljebb. Új fülön nyitja meg. Nem hallják a zeneszámot.

1–10 MB belefér videó. Meg kell osztani.

M365 steamből ágyazok be. M365-tel kell bejelentkezni.

Kézzel bedobálva, nem vagyok kész. Késznek jelölés elegendő. Rákattintok,
késznek jeölve nem biztos, hogy nézem.

Három pötyi a tartalomnál beállításokat szerkesztem. Film pl. beágyazva jobb.
Tanulónak meg kell nézni pipa. Moodle lejátszó teljes képernyő. Teljes értékű
lejátszó.

*** Szövegek
Lorem ipsum generátort használjuk.

*** Beszúrás szabályok moodleon kívüli dolgok
- pdf :: böngésző olvasója, új oldal vagy beágyazás
- kép :: png, jpg webes képek megjelenítése
- videó :: mp4 beágyazás és megjelníthető
- hang :: mp3 beágyazás.
- minden más :: böngésző nem kezeli, letöltődik.
- office :: offline vagy online. m365-ből behivatkozhatom. Egyetemi
  fiókkal.

Beállítják, hogy fenti legyen az automatikus!

*** Egyéb doksik moodleon belül
**** Oldal
Egyszerű. Olyan mint egy weboldal.

Leírást nem ad. Tartalomhoz lorem ipsum.

Képet tudok beszúrni. Képet random beteszem. Drag-and-drop megy.
Képleírás a digitális akadálymentesítés.

Kijelölöm és alpformázások mennek. Színeket még testre fogják szabni.
Ha színezgetünk ne nagyon. Dőlt és aláhúzott, akkor csínján. Dőltel szót ne
emelj ki. Balra zárt szöveg. Sorkizárt olvasási probléma, sortévesztés!

Nagyon sok szöveget ne egyszerre. Egy oldalon ne legyen gördítési sáv közben.
Ember szakaszt lefényképez, mint olvasási stratégia. Nem összeolasunk. Szakasz
lefényképez, és asszociatív módon kerül elő a szöveg. Minél hosszabb sor, annál
több fénykép, lassít. Margótól, margóig nem ergonomikus. Keskeny szöveg
gyorsan olvasható.
***** megjelenés
Megnyitás vagy előreugró ablakok. Mobilon nem megy. Reklám blokkolók lezárják.

Könyv jobb tananyagként!
***** Hasznos
Ami rövid ide megy. Tantárgy kimeneti követelményei. Oldal jobb mint pdf,
aktualizálhatom szerkeszthetem. Gyorsan megy a szerkesztés. Bármilyen tartalom
beágyazható benne. Bármi beágyazható. YouTube beágyazás.

YouTube és Vimeo együttműködik. Nem kell kódokat bemásolni. Tetszőleges szöveg
kijelölés és linket teszek rá.

**** Könyv
Behózott legyen elérhető korlátozott. Indul a könyv ekészítése.
Első fő fejezet. Ezt is lehet írni, ha egy órán belül elmentem.

Könyvnek a fejezetei.

Wordből is másolhatunk. pdf-ként menthető. Könyvtári kényelmi
szolgáltatás. Rákattintott a fejezetre. Nem tudom, hogy olvasta-e?

pdf olvasó lyuk a pajzson. Nem tudom mit csinál a hallgató.
Picit több, ha moodle könyvesítem a tananyagot. import from microsoft word.

Plugin fő és alfejezetet tud. Csak két szint van. Úgy írni, hogy minden
külön oldal Címsor1 vagy Címsor2. Stílusból választok.

Nem jó a címtorlódás címsor1-címsor2 után ne legyen!
Elarningben olyan szöveg, nagy téma előtt mi az oktatási cél. Megfogalmazzuk
és az előismereteket előírjuk. Teszttel mérhető. Könyvön belül H5P-s tesztek.
Csak önellenőrzés a diáknak.

Kiegészíthető! Még egyszer hangsúlyozzák. Interaktív fogalomtár használata is megy!
Fogalommagyarázat olalban vagy könyvben megy.

GDPR kompatibilis a hallgató tevékenységének figyelése. Vizsgáztatásnál pedig
fontos, hogy mindent lássak.

** Egyéb
*** Késznek jelölés
Dobozban, vagy automatikus, nyissa meg.
Meg kell írni a tesztet, és adott százalékot elér. Könyvnél véginézem az oldalakat.
Teszt csak akkor nyílik meg, ha beállítom a függőségbe. Irányított tanulás.

*** Elrejtés
A jobb oldali pöttyöknél, Elrejtés vagy megjelenítés.

*** PPT SCORM
ppt-t SCORMosítani kell. Ameriakai hadsereg találta ki. SCORMosítás fizetős és drága,

ispring scormosítás. Full screen és minden diára. email címmel regisztrál.

Sok hallgató pdf-re jegyzetel. Kiegészít. Amit többször el kell olvasni pdf.
Könnyen tanulható elairning forma, nehéz pdf letölt.

*** Mappa hozzáadás
Feladat készítése forrás dokumentumokból. 10x forrásból választ. Választást max
két ember választhat. Bedobálom az anyagokat. Ez kifejezetten külön oldalra.
Bármit kattintok akár egészben letöltheti.

*** URI
ritkán használják. Nevét megadom. Kötelező az URL. Automatikusan.

*** IMS
nem javasolják.

*** Címke
Téma blokk tagolására. Darabolni lehet. Altémák!

** Tevékenység teljesítése
Kurzus szinten beállítható. Portál szinten a következő verizó.

Kurzus főmenü kurzus kezelése

Tevékenység teljesítésének beállítása. Bedobálva automatikusan adja.
Jobb, ha a megtekintés az alapértelmezett.

* <2024-08-28 sze>
** Paár Dávid
Köszönt. Előzetes témakörök alapján ma is Csaba és Gyula.

Házi feladat és videók felkerültek. Külön rövid videók.

Zoli jött. Valami elektronikus kérdőív. Mindenki eldönti,
hogy mit szeretne.

Erről is lesz felvétel. Feldolgozható formában meglesz.
Chatbe írni, ha gond.

** Csaba

Feladatosítás és teszt íratás. Kapu drog, annak aki
szkeptikus. Papírral.

*** Központi kurzus
Fent vannak a videók.

Nagyon egyszerű feladatlista, Gyakorló feladat. 1. képzési napon.
Mindenkinek belepillantanak a gyakorló kurzusába. Nagyon sok anonim.

A 3. a kötelező adminisztráció.

Összes kibontás a kurzus jobb felső sarkában.

**** RRF kérdőív

RRF digitális kitöltés. Belépési és kilépési kérdőív.

Belépési kérdőív kérdések megválaszolása. Megnyílik az indok.
Itt 13 db kérdés. Azonosítás és elfogadom. Nem kell kitöleni.

Kitöltve.

*** Feladatosítás

**** Feladatok és beállításaik;
A második témát átneveztük feladatok, tesztek.

Évközben bomázzuk őket tennivalóval, hogy tanuljanak.
Tudásellenőrző tesztek. Önellenőrző, vizsga.

Már 30 éve halglató csinálta, leírta, bevitte. Nyomtatta,
digitálisan küldte. Napi 1-200 email mellett már nem jó
az email. Emailben kaptam beadandó. Más névről beküldve.
Nincs határidő kezelés. Problémás. LMS esetén online feladat.
Rendszer blokkolja, vagy feladat.

Saját gyakorló kurzusban dolgozunk. Tevékenység vagy tanagyag
beszúrása feladat. Feladatot meg is csillagozhatjuk, De megy a szűrés
is. Keresni is lehet.

Felső navigációs panel, mindig látjuk, hogy hol vagyok.
Új feladat hozzáadása, utána neve.

Feladatkíírásnál csak 3-4-et állítok.

Feladat kiadás, pontos feladatleírással. Ahogy tudod
fogalmazd meg, hogy milyen outputot szereetnék. 5 oldal
16-os betűtípussal csinálva. Karakterszám inkább. Szakdolgozat.
Ők így is bekérik. Értékelési módszert is megadni. Sima egyszerű
pontozást használjuk. 100 pontra beállítva. Meghatározom
magamban a mérőket, mennyiségi és minőségi. Miért kaptam
ötöst vagy rossz jegyet! Nem jegyet, hanem pontszámot
adok. Milyen szempontok alapján érétkelek.

Van tevékenység beírás. A feladat elvégzéséhez technikai.
Nem kell kitölteni. Régen nem létezett.

Kiegészítő állományok egy sablon vagy segéd adatok. Segédállomány
feltölthető a felületre is. A feladatba ágyazódnak. Mikortól
látja, szabályozható. Dolgozatnál jó a beidőzítés, hogy csak
a Zh írás időpontjában jelenjen meg.

Időpontok sokféle 4 különböző:
- leadás engedélyezése :: mikortól tudja beadni. Kevésbé fontos. Nem
  muszáj megadni. Mindig van alapértelmezett. Sokszor nulla óra. Nem
  egyértelmű a hallgatónak.
- határidő :: ez a kritikus. Meddig adható le. Beírja, hogy mennyivel
  később adja le. Persze vannak okok a késésre.
- lezár :: határidő mellett külön le is zárhatom. Onnantól nem adható
  le. Rendszer szintű bekapcsolható
- értékelésre :: Van oktató, aki akkor javít, amikor bejön. Saját
  magamnak emlékeztet. Nem kell élni vele.
- Leírás mindig jelenjen meg :: leírás és segédállomány elrejthető. Ha
  kiveszem, akkor a leadás engedélyezésétől egyáltalán nem látszik a
  feladat.

  
***** Leadás típusok
Állományban leadás vagy online szövet, de akár együtt is.

Grafikai elemek külön föltöltése is. Régen csak egy állományt
akkor tömörítve. Megadható, hogy hány állományt töltök fel.

Mekkora tárhely foglalást indikálok. Építészeti kurzus nagy
méretű műszaki rajz. Nagy kurzus. Itt 100 MB majd finomítják.

Onedrive és stream még lehetőség. 100 MB mindenkire szól.

***** Elfogadott fájltípusok
Mire korlátozom? Van választási lista. Beállítható.

***** Hallgató emlékeztető
Van hallgatói emlékeztető. Irányító pult folyamatos emlékeztető
felület Idősorral beállítható, hogy milyen határidős. Lehet bombázni a
hallgatók. Van valami plusz modul. Túl sok üzenet sem jó.
Nekem is bekerül a naptárba.

***** Visszajelzésí típusok
Szöveges ablakok visszajelző megjegyzések. Miért sikerült rosszul
magyarázata. Konkrét szöveges leírás a problémához. Mindig
bekapcsolva tartom.

Ráírhatok a pdf-re mintha papír lenne. Csak akkor működik,
ha beadott dokumentum jellegű. pdf-et ki szokta kapcsolni.
Van aki szereti.

****** Offline osztályozó
Ha nem moodleba javítok. Ki tudom egybe exportálni az összes feladatot
és offline munkalapba beírom az értékelést. Ahol nincs net ott
javítok. Visszajelzési állományokat is feltöltöm, vissza kóldöm a
javított állományt. Doksira tudok rajzoni az elsőnél. A visszajelző
állomány word korrektúra pl.

****** Sorközi megjegyzés
Online szövegnél és van szókorlát. És itt megy a sorközi
megjegyzés. Az ő szövegébe tudok jegyzeteket írni. Nem tudja
elmenteni, ha meghaladja.

Online szövegnél csak sorközi. pdf-é konveertálható word-nél
is lehet rájegyzetelni.

***** Leadás beállítás
Tanulónál a leadás gombra kattintás. Kis kérdőjeles sugó.
Nem javasolt igenre állítani. Feltöltésnél piszkozatként
kezeli. Nem ajánlják.

Leadási nyilatkozat elfogadásának kérése. Minden fájl előtt.
Központilag megfogalmazott dolog. Sokszor lehet hasznos, de nem
használják. Sokszor kikapcsolva, bekapcsolva a szakdolgozat digitális
példány begyűjtése.

Debrecenben központi plágium ellenőrzése. Rendszerbe integrálható
a plágium kereső. Könyvtár biztosít központi feltöltési helyet.

További próbálkozások. Ha a tanár már értékelte, lehet-e javítani?
további próbálkozások száma megadható. Általában nem engedem.
Konkrét hallgató esetében is meg lehetnyitni.

***** Csoportos leadás
Csoport szinten lehet leadni feladatot. 5 fős csapatokban
lehet leadni. Bármelyik csoporttag leadja, az a teljesítés és
a jegy mindenkinek bekerül a naplójába.


***** Értesítések
Tanuló leadja. Tág intervallum és kevés hallgató. Levelezőnél.
Kérhetek a lezártnál későkről értesítést.

Tanulók értesítése az osztályozás közben bejelölhető. Tanuló szereti,
elkezdem javítani. Első pontozásánál már kap emailt.  Amikor
lepontoztam, a többi érti. Egymást cukkolják, ha néhányat van időm
javítani. Kikapcsolható, s akkor nem kap direkt értesítést.

Tanuló értesítése több státusz


***** Pont
Értékelési folyamt. Nyugodtan értékelek, és nem engedem, hogy
visszajelezzen a tanulónak. Még egyszer egyedileg átbillenteni a
feladat esetén. Értékelési folyamatot használjuk, akkor én
szabályozok. Mindent kijavítom, és akkor adok ponthatárokat.
Utólag úgy döntök.

Lehet a feladat pontozás nélküli. Lehet szöveges skála.
Általam létrehozott szöveges skála megfelelt, nem felelt meg.

Leggyakrabban pontot használok. Megszokás és jogok. 100 minden,
vagy megtervezem, hogy hányat kérek be. És azt összedolgozom.

Van aki egy jegyet visszadob. Rögtön jegy. Pontszámot jeggyé
konvertálom. Leírásba beírom a pontozást, nem kell átszámolni, nem
lényeges. Szép matematikai képlettel. De lehet benyomás alapján.

Egyszerű közvetlen pontozás mellett rubrix értékelő tábla.  Részletes
kritérium rendszer, részletesen megcsinálom. Nagyon jól is lehet
használni. A4 tábla öt sorral, megadhatom. mely terület, ahol rosszul
teljesített. Táblát megcsinálni nehezebb. Több helyen is lehet
használni.

Munka egyszerűsíthető. ELTE PTK volt megállapodás, mit kell
értékelő táblázatnak tartalmaznia. Publikus sablonban mindenki
elérheti, kész sablont használom vagy módosítom.

Pontozási kategória, ha létrehozom. Évközi feladat, bármi
ami végső jegyhez járul, kategórizálom, súlyozni akarom.
Ha pöckölni akarom végtelen lehtőség, kevesen használják.

Pont a tlejesítéshez, megadok egy minimum pontot.


***** Tevékenység telejsítése
Később lesz a tevékenység teljesítése. Meg kell tekinteni,
osztályzatot kell kapni

Sok lehetőség van. Tanulónak visszajelzés. A teljesítés tényét
rögzíti. A renszernek is fontos, kell-e a tanulónak csinálni valamit
vele?

***** Szokásos modulbeállítások
Minden tanayagnál ugyan úgy. Látható vagy elrejtem,
elérhető, de nem jelenik meg. Csak linkkel hivatkozható.
Azonosítót adhatok neki, Rövid az osztálynaplóba kerül.

Csoport beállítása. Több neptunos tárgy összevonásával is
megy a csoportos dolog.

***** Cimke
Feladatnál nem használjuk, tesztnél fotnos.

***** Mentés
Mit látok?

Mit lát a tanuló? Mindig meg leet nézni, a jobb felső sarokban
magamra kattintva szerep átváltás. Nézhetem, hogy a hallgató
mit lát. Halglató szöveges kiegészítést adhat. Ahogy tegnap
néztük fel tud tölteni.

***** Teszt tanuló
Profil kép feltöltése. Teszt tanulót tudok beíratni.
Kézzel be tudom rakni

Látom a szerepköreit. Ki is tudom törölni a hallgatót.  Felhasználók
beíratása fönt. Tudok keresni. Egy-két hallgatót beerakni.

Biztonságos. Figyelmetlen oktató, mindenkit oktatóként írat be.
Oktató nem tud csak alacsonyabbat berakni.

Keresés név, neptun kód. Fel lehet venni teszt tanulót.

Látom a feladatnál, hogy mit adtak le.

Minden leadott munka értékelése.

Értékelés kacifántos módjai később.

** Szünet

** Kérdés válaszok
Korábbi kurzusok is megvannak, nem annyira triviális.
Lehet másolatot készíteni, amit a tanár készített.
Egyik kurzusból másikba is költöztethetünk tananyagot.

Csoportokhoz lehet külön feladatot rendelni.

Mappában forrásállományok. Válasz üzenet küldése a feladatban
egyedileg tudunk a hallgatóknak, csoportoknak
egyesével elküldeni a direkt leírást, amivel doglozni
kell. Nem mindent kell alapértelmezettet használni.

Vannak olyan tevékenység modulok, amit a diák szerkeszthet.

Teszt és feladat. Fogalomtár. Lehet diák munka. Fogalomtárnál
a diáktársak is látják, hogy ki mit küldött be.

Adatbázis, műhelymunka az stb keretében foglalkozhatunk. Nem
csak látják, hanem értékelhetem a munkát. Fórum használható.

Idősor és naptár minden hallgatónál megjelenik alapértelmezetten.
Illetve a naptár nem, csak az irányítópulton. Több helyen is
jelzi a rendszer, hogy mit kell csinálni.

Teljesítendő feladatok. A kurzusáttekintésnél van egy kész dolgot
mutató százalék. Mennyire van kész. Van olyan tevékenység, ami nem
neki szól. Nem adom ki a feladatot.  Teljesítés követését ki lehet
kapcsolni, százalék tájékoztató. Minél komplexebb kurzus annál
kevésbé exaktabb! Csak tájékoztató.

Kurzuson belül nincs idősor blokk. Portál szinten van értelme.
Kurzusnál naptár és események raktatók ki.

Valahogy lehet eseményt hozzáadni.

Át lehet hozni/hozatni a régi anyagokat.

Saját előrelátásomat a személyes menü beállításokban van. Az
elkövetkezendő események között látszódjon.



**** Teljesítési lehetőségek;
**** Kiegészítő teljesítési lehetőségek;
**** Értékelési típusok;
**** „Értékelési folyamat” használata;
**** A Teszt modul beállításai és alkalmazási lehetőségei;
Tesztek hogyan működnek, ahhoz a moodle működését érteni.
Már 20 éve volt a kezdetleges tesztrendszer.


Teszthez kérdések kellenek
***** Kérdések
Megírom wordben, vagy online rögzítem. Kellenek a teszt kérdések.

Kurzus felületén a tovább alatt kérdésbank. Teszt kérdéseket a
kérdésbankban kezeljük. Teszt kérdéseket több tesztben is
használhatjuk. Teremben más-más tesztet írnak.

Nadjet itt jött.

Valahogy randomizálással lehet játszani.

Adott tesztbe mi kerül. Manuálisan választom vagy véletlenszerűen.
Gyakorló tesztnél a szorgalmas tanuló többször nekifut. Idővel
minden kérdésből felkészül. Gyakorló tesztben kiadom a teljes
kérdésbankom.

***** Kérdésbank
Legördülő menü.
Importálás be tudom rakni pl. wordből. Itt lehet exportálni.

Kategóriák. Itt lesznek a kérdések, amiket létrehozunk.
Vannak különböző kategóriák, de nem látjuk.

Kérdések alapvetően kurzushoz kötődnek. Ha valaki magasabb
jogosultságú kategóriába szervezi a kérdéseket. A létrehozott
kérdések a magasabb kategóriából vehetem. Nem javasolhatják,
lehet chaos. Három oktató tanít. Kb ugyan azt kérik. Közös
kérédsbank. Kurzusok közös kategóriába kerülnek kategória
szintjén tudják használni. Koopeeráció. Akár minden kurzusból
látható kérdés van.

Lokális adminisztrátor jogosultsággal megy a külső kategória
nézés. Hierarchikus rendszerben tudunk építkezni.

Az 1. kategória. az alá alkategóriát lehet létrehozni.

Kategóriák fontos szerepet játszanak. Három tematikus
egységnek külön kategória. Első ZH elsőből. Melyikből
veszem a kérdéseket. Egyfajta tematikus kategorizálás.

Lehet másfajta bontás kérdéstípusok alapján. Kérdés alapján.
Ami nekem tetszik. Könnyű kérdések, összetett.

Kategórizálása alapja sokféle lehet.

Nem fogja a témaköröket kavarni, ha a kategória a randomizálás alapja.

Témánként is pontszám szerinti bontás. Véletlen szerűen bedobva,
minden kérdést egypontosít. Vissza lehet állítani a pontot
kategória alapján. Pontszám szerinti bontás. Ez segít a nehézségi
szinten összeállított dolgokról. Megálmodható kategória rendszer.

Oktató értse a kategóriát senki más nem látja. De segíti a teszt
összeállítást. Lehet a kategórát átstruktúrálni!



*** Kérdésbank szolgáltatásai;
**** A kategóriarendszer kialakításának a módszertana;
**** Kérdések


**** Kérdések szerkesztése:
Kérdés beírható.
Új kérdés létrehozésa 15-6 féle kérdéstípus.
Jelenleg alapvető kérdés. Használati gyakoriság alapján
rendezi be a kérdéseket.

Felelet választós több vagy egy jó válsz.
**** Alap kérdéstípusok létrehozása;
Csináljuk! Multiple-choice

Kérdés létrehozása sok kategória. Bonyolult elvinni, de nem kell minden.

Kérdés nevét nem látja a tanuló!!!! Nekem lehet segítség! Akár a jó
válaszra.

Kérdést számozzuk. Sokkal könnyebb megtalálni a szám alapján.
001-essel kezdhetünk. Sorbarendezés. Sokkal könnyebb megtalálni
javításnál a chaosban. Saját életünket könnyítjük.

Kérdéseken oktatói csoport dolgozik.

Kérdés állapota. Lehet tervezett is, nem rakja be éles tesztbe.
Alapértelmezett pot érték. 1 pont!

Általános visszajelzés. Van sok visszajelzés. A tanuló
teljesen önállóan gyakorlási céllal tölti a tesztet.
Utalás, hogy hol találja a választ. Lehet vélemény, illetve
rossz válasz. Csapdát magyarázom. Előadáson felhívtam
a figyelmet, hogy miért rossz?

Részben jó választ segít.

Papp Gyula: a hallgatók még több tananyagot kérnek, a második,
hogy önellenőrző teszteket kérnek. Sokat segít. A visszajelzés
kitöltése fontos. Rossz válasz esetén a tananyag megfelelő
részére mutató link is lehet. Megmutatom, hogy hol az információ.

Elég egy linkkel a megfelelő kurzus beli könyvoldara ugrani.

Azonosító szám utólagos azonosításban. Kelle külön tölteni? azt
mondták nem. A válaszlehetőséget keverje. IGEN!

Hogyan számozom. Van-e jelentősége a sorrendnek. Orvosoknál
az a) és a b) válasz együtt is jó. Ott nem kell keverni.

20 kérdés összekeverve a válaszokkal. Mást lát. 5c sugás nem megy.

Szokásos utasítás megjelnítése az egy-vagy több válasz jó
ezt írja be ki van kapcsolva, be lehet kapcsolni. Egy válasz
esetén nem lehet több.

A rendszer kever akkor mindig első lehet a jó. Egy jó
válasz, de lehet részpontokat adni a többi válaszra.
2/3 és 1/3 is van!

Hármasával növelhető, üreseket nem veszi figyelembe.

Vannak negatív pont értékek is. Többszörös felelet válasznál
van értelme.
***** Egyéb
Általános visszajelzés az alján

többször nekifuthat. Adaptív kitöltés. Ugyan azt megpróbálja.
Minden próbálkozással csökken a pontszám. Mindig kevesebbet
kap. Gyakorlónál nem megy.

Tippeket lehet adni. Mindig adok segítséget.

Hibás válaszok törlése. Megjegyezze a program, hogy már
tudja, hogy hibás. Meghagyja, ha rossz volt. Ritkán haszhájuk.
***** Cimkézés
Teszteknél van lehtősége. Rugalmasabb kategóriázálás, mint a
kérdésbank. Gmail cimkékhez! Egy levélre több cimke. Itt is így.

Kategória egy lehet. Cimkéből több is lehet. Tematikus, könnyű,
nehéz, gyakorló. Cimkenév és vesszőt nyomok, akkor automatikusan
ugrik. Három cike. Lehet a cimkék alapján keresni utána.
Szűrhetek és kereshetek. Lehet egy pontos vagy könnyű cimke.
Rugalmasabb teszt tervezés. Kevesen használják.

Szerkesztés előnézet.

Rendszer verziókatkészít. Ki hozta létre, szerkesztette,
módosította a kérdést. Statisztikai elemzések, megjegyzések.
Felülvizsgálandó mutató. Mennyire jó a kérdés. Sok rossz.

Milyen intenzitással.
***** Másik kérdés többfelelet választ.
Két jó válasz. 50–50%. Mind a négy választ bekattintja,
akkor megkapná a 100%-ot. Valamelyik csak jó lesz.
70 és 30 módon is megoszthatom.

Be kell írni a - pontot! Alapértelmezetten nem mehet negatívba!
De lehet beállítani, hogy lehet a teszt negatív is.

Szerkesztés helyett előzetes megtekintés. Úgy számolja, ahogy
én szeretném. Multiple choice büntető pontra gondoljunk!

Két jó válasz két roszz +- 50% Gyula nem engedi a negatívba
menést. Eü-ben bármely rossz, -100%

Kérdés viselkedési módok All-or-nothing. El van dugva.

**** Export/Import;
Kapunk egy csomó kérdést.

Aiken forma Wordban csinálhatom UTF8 kódolású fájl kell.
notepad++-t használ.

Be kell állítani a választ. ANSWER helyes válasz.
A formátumot beírja.

Legegzaktabb svg-be elmenti. Képként hozza be.
LaTeX kompatibilitás van.

Wiris képletszerkesztő hasonló. Weboldalon van.

Mi az amit importálok AIKEN GIFT moodle xml.

Mindig van egyfajta kötöttség.

Második kategóriába feltöltöm és importálás

Hátránya a kérdés nevében bent marad a számozás. Ki kell törölni!

XML saját környezettel beimportálom. Hozza be a környezetet
is. Saját kategória nevét behozza.

**** Teszt
Tananyag. Önellenőrző. Időkorlátot állítok be!

A tananyagra önellenőrző tesztet készítek, s ez segíti
a tanulást. Ki lehet szűrni a tipikus problémákat a
tanulócsoportnál, órán arra fókuszálni.

Tesztnél és önellenőrzésnél időkorlát. Tapasztalat megadja,
hogy egy tesztsor ennyi? 10 kérdés kb 2 perc 10 nagyon gavalléros.

A nyitott próbálosások leadása automatikus. FONTOS! A hallgató
helyett leadja a moodle.

Elfogadási szint gyakorlónál nem beállított. Korlátlan kitöltés
elrendezés egymás után. Kötetlenül bejárhatja, zászlócskázhat.

Minden kérdés saját oldalon gyakorlónak. vizsga ás.

Viszgánál nem tud visszatérni, ha nem kötetlen.

Kérdésen belüli keeerés igen?
Keverésnél egyiksem mindegyik. nem keverjük.

Bármikor visszajön. Önellenőrző kérdésnél helyes választ
nem mutatunk! Általános és globális visszajelzés a teszből
jön!

Megjelenés.

Biztonságos vizsgaböngésző vizsgatesztnél.

Jelszóval védett. Próbálkozások limitálása
Ne a teszten tanuljanak. A tananyagon.
1 naponként próbálkozás kivárás.

Évről évre jobb erredmény. Kérdés bankkal hogyan dolgozom,
védem vagy nem?

Globális visszajelzésnél vérremenő tesztelésnél.
Ponthatárnál.

Szokásos modul.

Elérhetőség

Tevékenység teljesítése.

Cimkének nincs jelentősége.

**** Vizsgateszt
vizsga 5 perc időkorlát.

Kézzel beválogatott. 1 szer kitöltöm.

Elrendezés kötetlen.

Kérdés viselkedése keverje.
- adaptív kérdés felülete ellenőrző gomb.
- adaptív levonás nélkül levonás nélkül
- azonnali visszajelzés nem
- CBM visszajelzéssel
- halasztott visszajelzés EZ AZ! csak leadás után
- interaktív többszöri, egyes kérdés típusoknál, tippek. esetleg
  önellenőrzőnél.

Csak pont és globális visszajelzés. Sokan kiszednek
mindent. Van betekintési alkalom. Ha bármi bent marad
a diák ellenőrizhet. Képernyő fotó. Elvittük a kérdést.

Bisztonságos viszgaböngésző.
Exam browser. nincs más. Csak a teszt megy.
Kevesebb csalás. Exam browser szerver.

Időkorlátot beállítani!

Böngésző teljes képernyős felugró ableak nem hagyhatja el.

Globális visszajelzés.

Tevékenység teljesítése. Kérdések hozzáadása. Válogatok.

Kézzel hozzáad 14 pontos teszt. 14 pont mennyi a teljesítéshez!

Tesztél figyelni az egy felelet választó. Helyes válasz
kikezdhetetlen sokkal hosszabb a helyes.

AI rossz kérdés generálásra.

**** Kiegészítő kérdéstípusok használata;
Vannak, jó tanácsok. 

* <2024-08-30 p>
** Paár Dávid
Kézi beíratás lesz.
Kristóf digitális módszertani.

** Csaba
Nincs még feladatsor. Nem élrték el a szervert ma pótolják.
Feladatokhoz van még néhány hét.

*** Beiratkozások
Neptun integráció nem teljes. Oktató eldöntheti, hogy mely neptun
kurzust szeretné moodle kurzust. Csak jövő héten lesz.

Másik fele, hogy egy kurzusban kiválaszthatja, hogy mely neptun beli
kurzussal szinkronizál. Sok-sok évvel ezelőtti dolog. Ne képződjön le
minden neptun beli kurzus. Sok hasonló vagy megegyező kurzs, ne legyen
duplán. Három gyakorlati kurzus ugyan az.

Jövő héttől hasonló szolgáltatás.

*** Debreceni példa
Résztvevőknél beíratkozási módszerek. Legördülő menüben a
résztvevőknél. Minden oktatónak saját feladata lesz. 1 perc/kurzus.

Kézi beiratkozás oktatók és 1-2 hallgató. Lassú. Lesz egy neptun
beíratkozás. Beállítási felület fogaskerék. Van egy általános felső része,
nem kell nyulni. Mikortól beíratkozás. Csak beíratás vagy leíratkozás is?

Ha hallgató felveszi, meggondolja, leadja, nem csak berakja, ki is veszi.
Normális, hogy be van kapcsolva, de nem mindig. Technikai limitálás itt is, de nem kell.
Automatikus üzenetküldés. Nem él vele. Kezdeti információhoz.

Adott félévre vonatkozó tárgyak. Be van kattintva. Mindig aktuális félév, de
vannak bent hallgatók. Itt beteszem, kiveszem a pipát, kiíratom és beíratom.

Több tárgy hozzárendelése. Ea és gyakorltat. Mindkettőt bekattintom.
Egy elarining felületre kerülnek. Magyar előadást is behúzta.

Félév elején beállítom és elmentem a beállításokat. Nem jelenik
meg akkor a 100 hallgató, amikor a hallgató először belép a
moodleba, akkor jelentkezik be. Leellenőrzi, hogy neptun kód alapján van-e,
ha igen, akkor beíratja. Az üdvözlő üzenet ezért jó. Továbbra is a
neptun az elsődleges kommunikációs felület.

Röviden:
- kurzusfelület
- résztvevők (aki már van)
- neptun és kiválasztom a tárgyat

Ezzel szinte megegyező megoldás készült, de nem tudják beéllesíteni.
Jövő heti kurzuson mutatják, illetve lesz róla videó.

*** Jelenleg működő
Hétfői indítás miatt, milyen megoldás? Van a lehető legkevesebb.
Megy egyeséve. Résztvevőket nézem.

Felhasználók beíratása a képernyő tegején és alján. Mindig van
nyilacska, ami visszavisz a tetejére.

Keresés mező. Vezetéknév keresztnév email vagy neptun. Hallgatók még nem nagyon vannak.
100 nál kevesebb találatnál mutatja meg. Így lehet nevet. Külön-külön lehet beírni.
Teljes név nem megy külön tárolja vezeték és kereszt nevet. Moodle ausztrál gyökerei
fordítva tárolja. Dániel Nagy működik. Angolszász.

Neptunkóddal is lehet keresni. Ez a legegzaktabb. Email cím is
teljesen jó. Csak alacsonyabb ranggal írhatható be. Van limitált is,
ami nem érdekes.

Jól működik, de lassul. 100 fősnél nem jó.

Jövő hétre már vannak. Saját beíratkozás engedélyezése. A hallgató saját
magát íratja be. Nem jelszó nélküli. Saját jelszót beállítani. Tangárgy ott,
és megvan a beíratkozási jelszó. Nem kell kitöltgeni.

Egyedi előfordulás a neve a saját helyett.

Beíratkozási kulcs a jelszó, ami alapján bejut a hallgató. Ez átmeneti
beíratkozás.

Minden elsős tűzvédelmi oktatás. Neptun pszeudo
tárgy. Nem kell keresni link, felveszi a tűzvédelmet.

Feltöltik-e a hallgatókat? Vannak még további módszerek. Később még
mutatnak megoldásokat.

Több oktatót nem lehet hozzárendelni. Neptunból kurzuskérésnél oktatót
átemelheti. Három oktatóból bármelyik kérheti.

Magunkat is kitörölhetjük.

*** Kis szem
Kis szem ikon láthat. Feltétel renszer, könyvoldal elrejtése is ilyen ikon.
Saját beíratkozás soha sem csukjuk ki a kis szemet. Kézi beíratkozásnál ne
csukjuk le. Mi is így vagyunk. Jelszóval bejött szemet lecsukjuk, akkor
ideiglegensen kivonjuk a forgalomból. Jobb a kurzus elrejtése. Nem a beiratkozás
elrejtése. Kurzus láthatóságát a beállításoknál rejtsük el. Vizsgáztatás idejére
elrejti a kurzust. Debrecenben van vizsgáztató portál.

*** Tesztek gyors volt
Vissza lehet nézni és kérdezni is lehet.

** Gyula

*** Profil információk
Kurzusban is lehetőség. Melyek amelyek a profilunkba tartoznak minden felhasználóra igaz.

Mindenkinek a renszerben profilhoz saját tevékenység, naplóbejegyzés van. Olyan beállítás,
ami az én kommunikációmat jelenti.

Profil információ a hallgatóknél is elérhető. Tanulási folyamatban teljes kontroll. Diákok
naplózva. Folyamatosan monitorozható, ki-mit csinál, akár az egész kurzus.

Más oktatásban naplózási technikák lesz.

**** Csengettyű
Gépi értesítés. Keveset kapunk. Feladatnál a hallgatói beküldésről kaphatok értesítés.
Sok hallgatónál sok. Itt sorjázknak.

A fogaskerék itt is van. Az én profilomhoz a technikai üzenetek hogyan érjenek el?
Párhuzamosan be tudom állítani. A weben akkor érdekes, amikor be vagyok jelentkezve.

Ilyenkor eseménynél, a képernyő jobb alsó sarkában krém sárga háttér. Felugró
értesítés. Csak röviden és rákattintunk. A másik ikon buborék.

**** Buborék
Emberektől érkező üzenet. Személyek közötti kommunikáció. Keresés a
diákra és felveszem a kapcsolati listámra.

Tutorálásnak is üzenetküldés, csapatnak is lehet csoportosan küldeni. Ezek az üzenetek is
itt megjelennek. Fórum és chat független az üzenetküldő rendszertől.

**** Nevem profil
Profilt ne szerkesszük. Nem kézi fiók. Komoly tiltások érévnyben. Gondot vet fel.

Itt is elérem a kurzusaimat.

Jelentések blokk. Minden hallgató profilját elérem. A jelentéseket látom.
Vázlatos jelentés. Az elhelyezett tananyagok közül mit néztem meg. Hallgatók is nézhetők.
Mindent amit a kurzusnál látok. Osztályzatok, értékelési tételek,

Le lehet ellenőrizni. Chatben üzenetek. Kijelzi a chatet.

Felvett kurzusok pontozásai is itt is megjelnik.

**** Profil Pontok
Hallgatónak érdekes.

**** Saját állomány
itt ne érdekes

**** Jelentések
Később érdekes lesz. Beállítatól

**** Beállítások

***** Blogok
Humán tárgyaknál főleg. Kurzustól független, becsatornázható a kurzusokba. Ki kell tenni
két kurzust. Bejegyzések a saját profilhoz. Blog cimkék kitétele. Szófelhő generálás.
Angolszászoknál tanulási napló. Diákok a tanultakra reflexiókat írnak. Szabad szöveg
gyártás, blog motorok. Külső blogot is be lehet húzni.

***** Szerepek
Milyen szerepek vannak. Bizonyos beállítás nem látszik. Portál beállítás függő.

***** Kitűzők
Intézményi szintű. Open badge szabvány áll. Mozilla kezelte, ma már globális szervezet
kezeli IMS global. One Learn ... Sok tag. Szabvány. Sok egyetemen használják a minősítésre.
Kézzel átadok kitűzőket. Fel lehet vinni.

***** Felhasználó fiók
profil szerkesztés, jelszó azure AD-ból.

Választott nyelv, jó ha tudjuk, hogy beállítható.

Fórumbeállítások Fórum nyomon követése új hozzászólások.

Szerkesztők beállítása
- TinyeMCE :: alapértelmezett nagyobb tudású.
- ATTO :: kártyák létrehozására

Naptár beálltás Mennyire néz át, mennyi esemény. Naptárral kapcsolatban
kint mutat majd még valamit.

**** Naptár kint
Be lehet állítani. Teljes naptár

Teljes naptár ide tudunk új eseméyneket ltrehozni. Mindent létre tudok hozni

Alján naptár import/export. icalendar. ics. iphone, outlook, google naptárba importálható.

**** Event reminder

Minden szerkesztett elemről értestés.
Egy kattintással értesítés.

Van egy pipálható mező. Tartalom megváltozásáról check-box. Kap egy értesítést, hogy megváltozott
a tartalom. Csak annyit ír, hogy változás történt. Mértékkel használjuk! Vizsga nevű teszt
megváltozott. Automatikus tájékoztató.

**** Feltételes tevékenység
Eddig mindig modul láttuk, korlátozásra felhívták a figyelmet. Az első tananyagra nem
állítok be korlátozást. Csak akkor tudom nézni, ha az elsőt teljesítem. Második beállítását szerkesztem.

Tevékenység korlátozása Korlátozás hozzáadása. Dátumok itt elérhető, dátudomok.
Osztályzat alapján. Beállítom, ha az önellenőrző tesztet teljesítetted.

IP cím korlátozása is van! Vizsga esetében egy adott teremre korlátozom az elérhetőséget.
Teszthez segédállományt, csak a tanteremben ülő lássa. Wifi-t is le tudom korlátozni.

Jelszóval korlátozom. Minden egyes elemet így védek. Pályázatban sok középiskolai tanárnak
tartalmat. Vendégként beíratás. Nincs fiók. Jelszóhoz kötik. Bárki bejön a kurzusba, jelszóval
védve van.

Felhasználóra is korlátozok.

Korlátozás készlet Minden modul korlátozásban. Megjelenik a feltétel. Tanárt persze
nem korlátozza.

*** Felvesze magam mellé nem szerkesztő tanárnak
Kollégák egymást felveszik. Nem oktató, vagy gyakorlatot tart. Ráépülő tárgy lássa.
Felveszik egymást, hogy lássák, mi a tananyag.

*** Folyt
Adaptív tanulás. Teljesítményre épül a korlátozás. Feladatnál mindig ott a hátráltató, amíg
nem értékelem. Inkább teszre jó. Következő tananyag akkor, ha megvan a teljesítés.

Minden alternatív tanyag elemre egy pontozási határt állítok be. 70% fölött1 alapértelmezett.
Alatta egy plusz szájbarágós modult kap. Szájbarágósabbat kap. Tovább lehet czicellálni. Többfelé
elbontom. Ellenőrző tesztnél be lehet sávozni a hallgatóknak.

Elérhetőség korlátozása, tevékenység. Több előfeltételt is be lehet írni. Éssel vannak betéve.
Midhármat teljesíti. Akkor megy.

Szemecskét lezárom, ez a tananyag addig nem látható, amíg a három feltétel nem teljesül.
A hallgatónak eltűnnek a ráépülő modulok. Diák identitását felveszi, mint rendszergazda.
Nincs ott a tananyag. Feltétel teljesül akkor jelenik meg.

*** Kérdések
Új dolgok, nem tudtam követni.

Választásként dobom fel. Nem egészen értettem.

Innentől nem jegyzeteltem. A kérdőíves dolgok voltak.

** Szünet

** Értékelés
Sok opció, kézi jegy berántása. Excel szerű dolgok.

* <2024-09-04 sze>
** Bevezetés
Belép, amikor bent lesz.

Kapok három kurzust.

** Profil fotó
Bepipálták az O365-öt.

** Koloszár Laci
Köszönt minket. Kieg oktatás. Fent lesz a videó.

** Csaba
Mára ütmezett tematika.

*** Neptun összerendelés
Neptun alapú kurzus összerendelés még nem 100%
Jelentős terhet vesz le.

Múlt hét pénteken célegyenesben fejlesztés automatizmus.
Kurzus létrehozása, ez még nem megy. A másik a hallgatók
kurzushoz rendelése. Ez már működő képes.

Mindenki saját gyakorló kurzusába nézni. Oktató tárgyai.

E-learningbe bekerül hallgató. Jelszót állítok. Bejön.

Elarning kurzusba azokat a hallgatókat látnám, aki felvette
ezt-és ezt a kurzust. Mit akarok összevonni. Ugyan az a gyakorlat
csak más napokon lehessen egybe kezelni.

Saját profilunkra kattintva.

Irányító pultra gyakorló kurzus. Tantárgy összerendeléshez
az oktatónak érvényes neptun kód kellene. Mi kurzusunkban adott!

Résztvevő fülön legördülő.
Beiratkozási módszerek kellenek. Itt kellene a neptun beiratkozás

Kiválasztom, akkor lekérdezi a kurzus összes oktatójának összes tantárgyát.

Tárgyak megjelennek a neptunban. Megynomom a gombot, nem
jelenik meg a hallgató a módszer hozzáadására. A rendszer
rögzíti az összekapcsolást. Itt megy a csoportkezelés is.
Nem kerül be prompt a hallgató. A tárgyat felvett hallgató,
ha belép, akkor a belépés után összeveti a neptunkódot és
berakja. Belépés váltja ki a beíratást. Beíratás és leíratás
is történhet. Automatikus leíratkozás is lehet. Van hallgatónak
mozgási szabadsága.

A regisztrációs időszakban automatikus megy.
Állapot kikapcsolás lecsukom a szemecskét. Hallgatók
nem látják a kurzust. Átmenetileg felfüggesztem. Inkább
a kurzust elrejtem.

Kézi hallgató neve mellett ott a kuka. Kézzel beírathatom. Neptunnál
nincs ott a kuka. Információs gomb kézi beíratás. Nem dobhatom
ki, itt lesz.

Félév végén a résztvevők beiratkozási módszerek, akkor a beiratkozási
mószert törlöm. Mindent lementettem, amit archiválni kell. Papír alapú
teszthez hasonlóan meg kell őrizni a hallgatók munkáját. Hogyan
dobjam ki, hogy megmaradjon. Félév közbe ne dobjuk ki, mert eltűnik
a teljesítménye.

Következő tantárgy újraindításnál szinkronizál és akkor mindenképpen
ki kell törölni. Nyomaikat is el kell tűntetni. Visszaállítás
funkció a tovább alatt.

Minden félév elején ezt a lépést meg kell tenni. Neptunba
felvette elarninbe, aki leadja szintén.

** Fogalomtár modul
Érintőlegesen már szóba került. Nagyon hasznos.
Fogalmakat tartalmaz. Hozzáadom.

Lehet több fogalomtárat is létrehozni. Lehet leírása.

Először lássuk a működését! Felviszem a terminus technikusokat
és magyarázatát rögzítem. Fogalom tár oldal, importálhatok is!
Helyben szerkeszthetem.

Kép beszúrása, adattárak böngészése. Wikimédia online
lexikon média tára. Szabadon felhasználható képek. Digitális
akadálymentesség miatt nevet kell adni. Kép és videó tartalomnál
hasznosak a leíró információk.

Köthetek hozzá más szavakat. Köthetek mellé más fogalmakat. Kulcsszó.

Automatikus kapcsolás központilag érdemes bekapcsolni.

Oldalban (egy oldalnyi szöveg).

Egy szövegben csak egy találat jelenjen meg. A kapcsolódóval
a szinonímáit kapom meg. Egy oldalon egy fogalom csak egyszer
jelenik meg! Ha nem akarom, hogy ugorjon rá. Ha van olyan, amire
nem akarom, akkor másik szövgszerkesztőben van egy hivatkozás
eltávolító ikon.

Interaktív összekapcsolás egy tetszőleges tudáshalmazzal. Könyvben
működik, tesztben is működhet. A fogalmat feloldja!

Kurzus szinten kikapcsolahtó. Kurzus tovább gombján szűrők.
youtube szűrő beállít. MatJax képletnek. Linket beírva automatikus.

Szójegyzék automatikus kikapcsolása. Teljes kurzusban kikapcsolja.
Vizsga idejére kikapcsolom.

Tesztben külön ki lehet kapcsolni. Önellenőrzőben segythet még.
A teszben is tovább szűrők kikapcsolása.

*** Fogalomtár
Lehet úgy is használni, mint kiadott feladat típus. Felviszik
a hallgatók. 50 halgató, 3 fogalmat dolgoz ki. Önkényesen választ,
írok egy fogalom listát. Válasz lehetőséggel választ. Mindenki
válasszon hármat. Dolgozza ki a tanuló. Felépül a fogalom tár.
Fogalmat értékelhetem.

*** Egyéb beállítások
Automatikusan hallgató szerkesztheti. Típusa a másodlagos
mellett lehet fő. Másodlagos a tanuló is írhatja. Ebből több is lehet.
Minden hónapba kidolgozható. Témakörönként fogalom gyűjtemény.

Az egész összefésülhető a főfogalomtárba. Csak az kerül
be, amit jóváhagyok, mint oktató. Fő és másodlagos fogalom
tárak között van exportálás funkció. A főbe kerül. A főfogalomtárba
a legjobbat küldöm. Alapértelmezetten nem része, ha nem alapértelmezett.

Bármikor szerkeszthető, akkor finomítható. Tanuló elmenti,
és nincs bármikor szerkeszthető, akkor később nem tudja.
Megjegyzéssel tudnak egymásra reflektálni.

Megjelenéssel tudom szabályozni, hogy hogyan jelenjen meg.
Egy lapra kiteszik...

Értékelés, ha feladatként adom ki.

Tevékenység teljesítésénél még be kell írni.

** Gyula
Még a fogalomtárról. Bekapcsolják a szerkesztést.
Fogalomtár ha nincs fő, létrehozva. szerkeszteni, ha van fő, akkor
exportálhatom a fő fogalomtárba. Diák szerkesztheti állományt
csatol, stb.

Akár tananyag kidolgozásra. Webes alkalmazások között
választhattak, leírás a többieknek. Az mehet itt, írhatják.

*** SCORM
ADL amerikai szervezet, hadsereg és fehér ház hozta létre.
2000 évek elején, hogy hogyan sztenderdizálják az elarninget.
2001 SCORM 1.2 szabvány ma is uralkodik. Milyen adatot
nyilvántartani, kommunikálni, feldolgozni a tananyagot.

ISO szabvány lett egy része. Elarining szakma örült neki.
Tananyag és keretrendszer gyártók örültek. Tananyag pályázati
kiírás szabvány a kiírásban elhangzott!

Mivel csinálom iSpring (egyik legolcsóbb). Quis maker,
SORM-os teszt leehet. PPT-ba beépülő. Kamera videófelvétel,
megvágom. Komponens berakása. Komponensek berakhatók

Storyline 360 ez külön alkalmazás, ez is PPT-be épült? Layout
a látványos tananyaghoz.

Adobe Captivate legújabbat nem érdemes megvenni 2019 sokkal
flexibilisebb, de nehezebb dolgozni benne.

Fentiek 1 licenc 1 gép.

ispirngfree ppt-ba épül exportálni tudja. Előadás figyelemfelkeltő
és kevés szöveg. Tananyaghoz kell a szóbeli előadás beírva.

Tananyag kisebb betűvel és kevesebbet írok. Ingyenesen. ppt-t
exportálja és fullscreenben kiküldhető.

Másik eXeLearning XHTML editor. Böngészőbe épül be és ott
nyílik meg. Szövegcentrikus. Oktatási eszközöket csinál.
Scormtest, ami kommunikál a keretrendszerrel.

Moodle SCORM lejátszó. Moodle SCORM 1.2 hitelesítéssel rendelkezik.

Tevékenység között egy dobozocska. Csomag. Zip állomány feltölthető.
Ad egy nevet neki. Leírást ad hozzá, utasítás és jótanácsok.

Ad utasítást, pl: kattintson a prezire, elindul a köztes animáció.

Feltölti a scorm2.zip-et Hogyan jelenjen meg? Aktuális
oldalon belül. Javasolja, hogy új ablakban. Felugró ablak,
meg kell tanítani, hogy engedjék a portálról a felugró ablakot.

URL gátolt ablak, kis ikon feloldom.

Megjelenés 100% x 100% széesség magasság, töltse ki az ablak
a képernyőt. Ha mindenki tudja mit kell csinálni, akkor
a megadott dolgokat ugorja a leírásnál.

Előzetes kikapcsolása igen!

eXeLearningnak kell az Oldalra. A többinél kikapcsolva.

Pont, csak a tudás egység alapján tud adni. Minden HTLM oldal,
annyi pont. eXeLearning ahány oldal, annyi pont. Sok oldalból,
a többi egy ablakban 1 oldal, azon belül laponak (fizetős).

Újrapróbálkozás valami üzletinél (articulate) nem lehet nem

A tevékenység teljesítése.

ispring nem tudja átadni.

Ha nem lejátszható, akkor hibaüzenet.

Belépés a tananyagba.

Szabvány szerint nem lehet elágazás.

SCORM mindig külső eszközzel kell készíteni. Moodlenél
még részletesebb naplózás a lejátszás során. Minden interakció
rögzítve. Adobe kattogást nézi. Végiglapozásra nem enged a captivate.
Minimális értékig kell nézni az oldalt. Nem működik a gomb, amíg ki nem
várom az időt. Full multimédiás anyag.

*** Kommunikációs eszközök

**** Fórum
Sokat fog létrehozni.

Sok típus van a fórumon.

Általános, ahogy elképzeljük, kérdés és válasz rá.

vitatéma megadás, standard, fórum.

Tól-ig tart a vita, érveljenek a hallgatók.
Vádló és védő oldal, érvelni mellette és ellene. Feladat!

Akár melléklet vagy szószám beírható. Mennyi az annyi?

Fél óra után kimegy a bejegyzés.
Feliratkozás kikapcsolva, akkor nem megy levélben.

Szószátyár hallgatókat blokkolhatom.

Kötelező, s mindenkitől elvárok 1 választ legalább.

**** Kérdések megválaszolása fórum
Fórum működésének leírása...

Kötelező feliratkozás.

Új vitatémát indítok. Mindenkiről tudni akarom, hogy válaszol-e?

Jazz quiz, ea time quiz sem tökéletes az igényeknek.

**** Chat
Annyira nem javasolja.
Pl. Online fogadóóra. Korábbi üzenetet csak az nézheti,
aki részt vett rajta. A hőskorban zseniális volt.

**** RSS
Portál szinten kell bekapcsolni.

Tvitter és RSS nincs magyarországon. Lényege, hogy hegy nem
megy mohamedhez, mohamed hegyhez. A hír megy hozzám. Sok
idő, hogy kedvenc témák után kutatok. Sok mást elolvasok.

Ha érdekel, akkor be tudom illeszteni.

hvg rss oldala. Van az edu-linenak?

Blokk hozzáadásával tudom megcsinálni, lehet blokk hozzáadásával.

Távoli hírblokk beállítása, hír hozzáadása.

Egyetemi hálózatból tiltva van. Ez külső.

RSS kompatibilis blokkok beállítható. Fogalomtár is lehet RSS
alapú. RSS hírek a szerveren bekapcsolva. Új hír hozzáadása.

Minden ami hír, ki tudom vinni RSS olvasóba.

*** Üzenetek
Majdnem olyan mint a csevegés, de nem kell szinkron, kimegy az
email.

Hallgatók lehet a résztvevőknek. Kiválogatva.

Portál üzenetküldés funkcióját használja.

Aki nem nézte meg, annak írhatok üzenetet. Rá tudok írni.

Tudok megjegyzést adni a hallgatóhoz. Akinek papírja, fogyatékkal
élőr, annak kell plusz időt.
Vizsgánál felhasználónként felül tudom írni a doglokat. Kivételt
tehetek, pl. teszt esetében.

A harmadik nap feladat már elérhető.

Attila offline.

* <2024-09-05 cs>
Díjkiosztó volt. Sok mindenre nem tudtam utána figyelni,
mert Biró Máté Bencével beszélgettem.

** Műhelymunka
Papp Gyulával

Közben csatlakoztam be.

Ha nem adják le, vagy késlekednek gond!

Diákok értékelnek!

Pontozás értékelési szakasz. Értékelési pontok. Tevékenység összegzésének megírása.

Ígérte, hogy minden hallgató nevében ad le feladatokat.

** Wiki
Tevékenységek között, bár ritkán használják. Mint a wikipédia.

HTML wikit javasol.

Prios az oldalban, amit meg kell magyarázni. `[[ ]]` 

** Neptun kód
Reggel 8-kor belép, nincs a belépés pillanatában, minden éjszaka befut.

Éjszaka fut le a script, aki kitölti a neptun kódot.

* <2024-09-11 sze> 6. képzési nap
Teams gondok voltak.

Automatikus kurzus kérés.

Szept 5-i képzés linkjén vagyunk.

Pannon Egyetem lesz holnap

* Lecke modul
Összetett és izgalmas.

Furcsa kifejezés Lesson angolul. Nem fedi a magyar leírás
a funkcianiltást. Lecke professzionális tanulás irányítás.

Leckét tervezni kell!!! Sok modulból állhat. Leülök és gondolkodok
és A4-es papíron firkálok. Nagyjából szemléltetni kell.

Több elemből álló irányított, potenciális elágazásos. Elágazás
jellemzően tudás ellenőrzést követően.

Tananyag -> tananyag -> Kérdés -> elágazás vissza vagy ismétlő szájba
elágazás 2 újabb tanyanyag -> másik kérdés

Lehet esettanulmány feldolgozása is.

Elérhetőség feltétele másik tananyag áttekintése! Kurzus szintjén
is van. Leckében egy tananyag egységen belül irányítok.

Kevesen használják, mert gondolkodni kell és tervezni.

Lecke ikonja. Egymást követő pöttyök és bejárás.
Megjelenés, folyamatjelző hány százalékot teljesített.

Bemutató a lecke fel volt készítve ppt importra. Adobe Flash
feldolgozása. Minek használom? Tananyagot készítek.
Hagyományos elearning kis tananyag kis önellenőrzés.

Aktuális pontszám folyamatos, bizonyos százalék után
menü. Quiz, de inkább igaz, hamis, feleletválasztó 5-ös.

Legyen-e visszacsatolás? Külső tevékenységgel összekötni.
Időkorlát, ha vizsgáztatok.

Moodle mobil applikációja offline letöltésre. Ingyenes
moodle kurzus 2 db offline. A leckét a telefonon is
megoldhatom online.

Hányszor tudnak nekifutni?

Elágazás előretekintés izgalmas, ha csak 1.

Gyakorló leckénél nem pontoz!

Teljesítés feltétele változatos. Sok út és elágazás
esetén nem biztos a végére érek.

Elmentés után lecke szerkesztése.

Oldal címe 1. oldal Leírás a navigációhoz, és hová kerüljön.
Tovább ugrások megtétele, kell gomb.

Melós. Egyébként a tananyagot tervezni kell, leckénél
komolyan! Itt kétszer végig menni, hogy bedrótozni!
Ugrások oldalra fixálása.

Van nézete kibontott tartalmi elemekkel.

Menü bekapcsolása esetén lehet szabadon ugrálni.

Van potenciál, de komoly időbefektetés. Tanulásra és
számonkérésre alkalmas.

Tömb több elembből áll. Kell kezdet, vége és tartalma.
Kihagyott kérdés egy tömbben. A kérdések összefogása.

Tömb több kérdés alapján tudom, hogy elsajátította-e a tananyagot?
Tömbből kimutatni nem lehet. Hallgató illegális navigációja.
Tömbben a kérdések kérdésekre. Midre helyesen válaszol,
akkor lehet kimenni.

Videó végignézése, ha 1 tartalmi blokk, 20 perc.
H5P interaktív videó jobb.

YouTube bárki nézheti O365-nél csak az intézményhez
rendelt hallgató. Vannak kényes videók. Van képernyő rippelő
szoftverek, bármilyen tartalom elvihető.

Film nézésének kikényszerítése moodleban nem megy, komolyabb
eszköz. H5P is alkalmas, H5P komm szolgáltatás esetén!

Scorm elveszi a navigációs eszközöket.

YouTube vezérlő elrejthető, de megkerülhető is.

** H5P alapismeretek
Holnap folytatják

* <2024-09-12 cs>
** H5P
Interaktív videó. Egyszerű és felhasználó barát szerkesztő
felület.

Tartalom bank csak H5P-nél. Példákat mutatna.

*** Elhúzható műholdkép
Két kép elhúzva. Csak fel kell tölteni a két képet.

image-juxtaposition.

*** Timeline tartalomtípus
Interaktív timeline. idősávok között szabdon ugrálhat.

Földtörténeti korok. Több dolog egymáson! Egy objektum
jelenik meg a timelineon.

*** Memória játék
Játéknak álcázott tanulási folyamat. Sok infót lehet berakni.
Párra kiírja az infót.

*** Elágazásos
EU művészettörténete. Nagy lapon dolgozok, sokféle
esettanulmány. Segít a szerkesztésben.

*** Image hotspot
Küslő link és tartalom.

*** Interaktív videó
YouTube videó megjelenítése, reklám a tananyagban. Nekik
van saját streaming. Interaktív pontok.

Nem kerül be az osztályzónaplóba. Ébren tartja a tanulót.
Tud blokkolni. Rákényszeríti, hogy nyitott szemmel nézze.

Egyelőre vagy feltöltött videó vagy youtube. Mikor kezdődjön?

Közbe jött egy kolléga, s innen nem tudtam követni.

** Látványos kurzus
Moodle saját szerkesztő rendszerében található szépítő
eszközök. Látványelemek szövegekhez.

* <2024-09-18 sze>
** Importálás
Ahonnan, ahová, mindkét helyen oktató.

Hasonló kurzusba hasznosítható elemek.
*** Standard
Tovább -> Kurzus újbóli használata.
Első az importálás. Forráskurzus választása.

Korábi kurzusállomány. Kihalt.
Rég: Szerver moodledata könyvtár. Fájltárolóban láthattunk mindent.
Ma: Kettestől titkosított állomány. Fájltároló.

Következő szelektív áthozás

*** Tananyag vágólap

*** Lomtár
Központilag kezelhető. Főmenü tovább alá, törés.

Cron futás után meg fog jelenni. Percenként lefuttatott
tevékenység lista.

Végleges törlés és helyreállítás.

Teszt rengeteg anyag. Eltűnhet! Teszttel óvatosan!

** Jelentés
És sok minden. Rengeteg információ nyerhető.
A lényeg a diák tevékenységén legyen rajta a kezem. Ez
ad értelmet az elarning használatának. Tudjam, hogy mi
történik a kurzusban. Milyen problémák vannak a tananyagban?

Mo. a diákok az oktatót ritkán kérdezik. Félrekommunikáció.
Nem tiszta a helyzet.

*** Alapstandard eszközök
Jelentések menü! Sok modul.

**** Naplók
Szűrő lista. Időt és dátumot látunk. SOE Admin nem ember, de
be lehet jelentkezni.

Eredet CLI automata esemény, ami a kurzust érintette.

Mobil alkalmazás is itt van. web, vagy mobil. Radikális
eltérés. Ki végezte a műveletet, mely felhasználó.

Moodle mindennek van azonosítója id= kurzusnak, modulnak.
Résztvevők, napok...

Letölthető! Excel stb.

**** Élő naplózások
Felügyeleti eszköz.

Nincs feltüntetve a szűrő lista. De az aktuálist mutatja.
Teszt íratásnál látszik, tevékenység nyomon kísérhető.
Teszt mellett megjelenik egy könyv. Online puska!

Azonnali frissítés van!

**** Kurzustevékenység
Felül az év, utána későbbi időpontok.

Haladnak a diákok. Könyv, teszt, fogalomtár sokszor megtekinthető.

**** Kurzusrészvétel
**** Tevékenység végrehajtása
**** Görbe
Kurzus használat intenzitás, ha globálisan bekapcsolva, nem
folyamatos frissítés, erőforrásigényes.

*** Ha nem megy
Kurzus tevékenység figyelése.

Tevékenység teljesítés alapbeállításai.

Teljesítés tömeges beállítása. Minden oldal és
könyv. Linkek. Állomány.


*** Haladó forma

Teljesítés visszaállítása, Felhasználó listából visszatöltve.

Részletes megnézése, modulonként! Hallgatónként!
Résztvevők, tanuló, teljes!

** Admin
Mentés.

Rejtett kurzus, nem tud hallgató belépni.

Benne csücsülnek a allgatók.

Neptun alapú beíratkozást törlöm. Akik neptunnal jöttek, a
felületen nem érhetők el.

Kézi felhasználók és neptun a visszaállítás!
Nincsen fórum, teljesítés, stb. Meglévő logokat, stb.

Adatbázisban törli. Visszaállítás adatbázisból töröl!

Kell egy teljeskörű biztonsági mentés vitás helyzethez.
Mit akarok törölni?
Megjegyzések kurzusban, illetve oktató által hallgatóról rögzített.
Fogyatékkal él, kreditelfogadása van!

Hallgató kitörlése.

Kurzus összes felülírását, összes helyi szerepet!

Fogalomtár és export!

Kövi szemeszter, rejtettből látható, neptun beíratás.
Tevékenység eredményei

** Geogebra
Akik matematikai irányból közelednek.

Bekapcsolt szerkesztés. Tevékenységek között.
Speciális feladat modul.

https://tananyag.mdoe.hu

megvannak neki az állományok ggb!

Bonyolult dolgokat is lehet csinálni. Függvény ábrázolás,
geometriai problémák!

Szerző beadja a pixelméretes. Általában magasságot
mondunk!

Tevékenyésg a harmadik automatikus!

A felhasználók AzureAD-ból kerülnek be!
